# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  bng-register-web:
    build:
      target: development
    image: bng-register-web-development
    container_name: bng-register-web-development
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
    environment:
      AZURE_STORAGE_CONNECTION_STRING: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://bng-register-web-azurite:10000/devstoreaccount1;
    depends_on:
      - bng-register-web-azurite

  bng-register-web-azurite:
    volumes:
      - azurite_data:/data
    ports:
      - "10000:10000"

  redis:
    image: redis:4.0.14
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  redis_data:
  azurite_data: