services:
  bng-register-web:
    build:
      context: .
      target: production
    image: bng-register-web
    container_name: bng-register-web
    environment:
      APPINSIGHTS_CLOUDROLE: bng-register-web-local
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
      REDIS_HOSTNAME: redis
      COOKIE_PASSWORD: cookiecookiecookiecookiecookiecookie
