environment: production
environmentCode:
name: bng-register-web
namespace: bng-credits
workstream: bng-credits
image: bng-register-web

labels:
  component: service

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID

appInsights:
  connectionString:

containerConfigMap:
  name: bng-register-web-config-map

containerSecret:
  name: bng-register-web-container-secret
  type: Opaque

deployment:
  cpuThreshold: 80
  memoryThreshold: 80
  minReadySeconds: 0
  minReplicas: 1
  maxReplicas: 1
  priorityClassName: low
  replicas: 1
  restartPolicy: Always

container:
  requestMemory: 100Mi
  requestCpu: 100m
  limitMemory: 100Mi
  limitCpu: 100m
  port: 3000
  azureStorageAccountName: bngregister
  azureStorageConnectionString: dummy
  azureStorageUseConnectionString: false
  azureStorageCreateContainers: false
  cookiePassword: who-likes-cookies-i-like-cookies-everybody-likes-cookies
  imagePullPolicy: IfNotPresent
  redisHostname: redis-hostname.default
  redisPartition: bng-register-web
  redisPassword: redis
  redisPort: 6379

ingress:
  class: nginx
  endpoint: bng-register-web
  server: value.replaced.from.app.config

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

service:
  port: 80
  type: ClusterIP

aadPodIdentity: true
