environment: production
environmentCode:
name: bng-register-web
namespace: bng-register
workstream: bng-register
image: bng-register-web

labels:
  component: service

appInsights:
  connectionString:

containerConfigMap:
  name: bng-register-web-config-map

containerSecret:
  name: bng-register-web-container-secret
  type: Opaque

deployment: {}

container:
  requestMemory: 100Mi
  requestCpu: 100m
  limitMemory: 100Mi
  limitCpu: 100m
  port: 3000

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5
